apiVersion: v1
items:
  - apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    metadata:
      annotations:
        meta.helm.sh/release-name: prometheus
        meta.helm.sh/release-namespace: observable
      creationTimestamp: "2022-08-18T11:46:23Z"
      generation: 7
      labels:
        app: kube-prometheus-stack-prometheus
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 35.5.1
        chart: kube-prometheus-stack-35.5.1
        heritage: Helm
        release: prometheus
      name: prometheus-kube-prometheus-prometheus
      namespace: observable
      resourceVersion: "1174931874"
      uid: 21a6114f-013c-47b6-8e20-c32c96c1c848
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: pool-type
                    operator: In
                    values:
                      - observable
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: prometheus
                    operator: In
                    values:
                      - prometheus-kube-prometheus-prometheus
              topologyKey: kubernetes.io/hostname
      alerting:
        alertmanagers: []
      disableCompaction: true
      enableAdminAPI: false
      evaluationInterval: 30s
      externalUrl: http://prometheus-kube-prometheus-prometheus.observable:9090
      image: quay.io/prometheus/prometheus:v2.35.0
      listenLocal: false
      logFormat: logfmt
      logLevel: info
      paused: false
      podMonitorNamespaceSelector: {}
      podMonitorSelector:
        matchLabels:
          release: prometheus
      portName: http-web
      probeNamespaceSelector: {}
      probeSelector:
        matchLabels:
          release: prometheus
      replicaExternalLabelName: ""
      replicas: 3
      resources:
        limits:
          cpu: "6"
        requests:
          cpu: "6"
      retention: 1d
      routePrefix: /
      ruleNamespaceSelector: {}
      ruleSelector:
        matchLabels:
          release: prometheus
      scrapeInterval: 30s
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: prometheus-kube-prometheus-prometheus
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector:
        matchLabels:
          release: prometheus
      shards: 1
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 30Gi
            storageClassName: managed-csi-retain
      thanos:
        objectStorageConfig:
          key: thanos.yaml
          name: thanos-objstore-config
      tolerations:
        - effect: NoSchedule
          key: pool-type
          operator: Equal
          value: observable
      version: v2.35.0