apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-deployment
  namespace: devops
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: debug
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
        - command:
            - sleep
            - '360000000'
          image: 'nicolaka/netshoot:latest'
          imagePullPolicy: IfNotPresent
          name: debug
          # --- 添加 lifecycle hook 从这里开始 ---
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "echo 'Installing Go...'; apk update && apk add go; echo 'Go installed successfully.'"
          # --- 添加 lifecycle hook 到这里结束 ---
          resources: {}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30