apiVersion: v1
data:
  allow-backend-server-header: 'true'
  enable-underscores-in-headers: 'true'
  generate-request-id: 'true'
  ignore-invalid-headers: 'true'
  log-format-upstream: >-
    $remote_addr - [$remote_addr] - $remote_user [$time_local] "$request"
    $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length
    $request_time [$proxy_upstream_name] $upstream_addr
    $upstream_response_length $upstream_response_time $upstream_status $req_id
    $host [$proxy_alternative_upstream_name]
  max-worker-connections: '65536'
  proxy-body-size: 20m
  proxy-connect-timeout: '10'
  reuse-port: 'true'
  server-tokens: 'false'
  ssl-redirect: 'false'
  upstream-keepalive-timeout: '900'
  worker-cpu-affinity: auto
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"allow-backend-server-header":"true","enable-underscores-in-headers":"true","generate-request-id":"true","ignore-invalid-headers":"true","log-format-upstream":"$remote_addr
      - [$remote_addr] - $remote_user [$time_local] \"$request\" $status
      $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $request_length
      $request_time [$proxy_upstream_name] $upstream_addr
      $upstream_response_length $upstream_response_time $upstream_status $req_id
      $host
      [$proxy_alternative_upstream_name]","max-worker-connections":"65536","proxy-body-size":"20m","proxy-connect-timeout":"10","reuse-port":"true","server-tokens":"false","ssl-redirect":"false","upstream-keepalive-timeout":"900","worker-cpu-affinity":"auto"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"ingress-nginx"},"name":"nginx-configuration","namespace":"kube-system"}}
  creationTimestamp: '2025-07-02T05:31:29Z'
  labels:
    app: ingress-nginx
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:allow-backend-server-header': {}
          'f:enable-underscores-in-headers': {}
          'f:generate-request-id': {}
          'f:ignore-invalid-headers': {}
          'f:log-format-upstream': {}
          'f:max-worker-connections': {}
          'f:proxy-body-size': {}
          'f:proxy-connect-timeout': {}
          'f:reuse-port': {}
          'f:server-tokens': {}
          'f:ssl-redirect': {}
          'f:upstream-keepalive-timeout': {}
          'f:worker-cpu-affinity': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app': {}
      manager: ACK.RC
      operation: Update
      time: '2025-07-02T05:31:29Z'
  name: nginx-configuration
  namespace: kube-system
  resourceVersion: '120668596'
  uid: aafdc5ab-dc85-4fd2-ac55-b618053b860b
