apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-cni-install
  namespace: istio-system
spec:
  components:
    cni:
      namespace: istio-system
      enabled: true
  values:
    cni:
      logLevel: info
      excludeNamespaces:
        - istio-system
        - kube-system