apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ambient-telemetry-patch
  namespace: istio-system
spec:
  profile: ambient
  components:
    pilot:
      k8s:
        env:
          - name: PILOT_ENABLE_ECDS
            value: "true"
  meshConfig:
    enableTracing: true
    extensionProviders:
      - name: otel-tracing
        opentelemetry:
          service: opentelemetry-collector.observable.svc.cluster.local
          port: 4317