apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: otel-provider-patch     # 名字随意，只要跟现有的不冲突
spec:
  profile: empty                # 关键！不带组件
  meshConfig:
    enableTracing: true
    extensionProviders:
      - name: otel-tracing
        opentelemetry:
          service: opentelemetry-collector.observability.svc.cluster.local
          port: 4317