apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
        - name: envoy
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100
      customTags:
        deployment_name:
          environment:
            name: ISTIO_META_WORKLOAD_NAME
            defaultValue: ""
        pixcc_client:
          header:
            name: "pixcc_client"
            defaultValue: ""    