apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: observable
  creationTimestamp: "2025-03-02T11:27:53Z"
  generation: 6
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 69.2.2
    chart: kube-prometheus-stack-69.2.2
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-prometheus
  namespace: observable
  resourceVersion: "43892783"
  uid: fe7a63d2-f388-4c1f-b76d-8435a2f60e48
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - prometheus
                - key: prometheus
                  operator: In
                  values:
                    - prometheus-kube-prometheus-prometheus
            topologyKey: kubernetes.io/hostname
          weight: 100
  automountServiceAccountToken: true
  disableCompaction: true
  enableAdminAPI: false
  evaluationInterval: 30s
  externalUrl: http://prometheus-kube-prometheus-prometheus.observable:9090
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v3.1.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: prometheus
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: prometheus
  replicas: 1
  resources:
    limits:
      cpu: "6"
    requests:
      cpu: "6"
  retention: 1d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: prometheus
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: prometheus
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: prometheus-kube-prometheus-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  shards: 2
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512Gi
        storageClassName: oci-bv
  thanos:
    blockSize: 2h
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config
  tsdb:
    outOfOrderTimeWindow: 0s
  version: v3.1.0
  walCompression: true
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2025-04-29T05:04:38Z"
      message: ""
      observedGeneration: 6
      reason: NoPodReady
      status: "False"
      type: Available
    - lastTransitionTime: "2025-04-29T05:04:38Z"
      message: ""
      observedGeneration: 6
      reason: ""
      status: "True"
      type: Reconciled
  paused: false
  replicas: 1
  selector: app.kubernetes.io/instance=prometheus-kube-prometheus-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=prometheus-kube-prometheus-prometheus,prometheus=prometheus-kube-prometheus-prometheus
  shardStatuses:
    - availableReplicas: 1
      replicas: 1
      shardID: "0"
      unavailableReplicas: 0
      updatedReplicas: 1
    - availableReplicas: 0
      replicas: 0
      shardID: "1"
      unavailableReplicas: 0
      updatedReplicas: 0
  shards: 2
  unavailableReplicas: 0
  updatedReplicas: 1