apiVersion: v1
data:
  merged-values: |-
    {
      "affinity": {},
      "autoscaleBehavior": {},
      "autoscaleEnabled": true,
      "autoscaleMax": 5,
      "autoscaleMin": 1,
      "base": {
        "enableIstioConfigCRDs": true
      },
      "cni": {
        "enabled": false,
        "provider": "default"
      },
      "configMap": true,
      "cpu": {
        "targetAverageUtilization": 80
      },
      "defaultRevision": "",
      "deploymentLabels": {},
      "enabled": true,
      "env": {},
      "envVarFrom": [],
      "experimental": {
        "stableValidationPolicy": false
      },
      "extraContainerArgs": [],
      "gatewayClasses": {},
      "gateways": {
        "istio-egressgateway": {},
        "istio-ingressgateway": {},
        "seccompProfile": {},
        "securityContext": {}
      },
      "global": {
        "caAddress": "",
        "caName": "",
        "certSigners": [],
        "configCluster": false,
        "configValidation": true,
        "defaultPodDisruptionBudget": {
          "enabled": true
        },
        "defaultResources": {
          "requests": {
            "cpu": "10m"
          }
        },
        "externalIstiod": false,
        "hub": "docker.io/istio",
        "imagePullPolicy": "",
        "imagePullSecrets": [],
        "istioNamespace": "istio-system",
        "istiod": {
          "enableAnalysis": false
        },
        "logAsJson": false,
        "logging": {
          "level": "default:info"
        },
        "meshID": "",
        "meshNetworks": {},
        "mountMtlsCerts": false,
        "multiCluster": {
          "clusterName": "",
          "enabled": false
        },
        "network": "",
        "omitSidecarInjectorConfigMap": false,
        "operatorManageWebhooks": false,
        "pilotCertProvider": "istiod",
        "priorityClassName": "",
        "proxy": {
          "autoInject": "enabled",
          "clusterDomain": "cluster.local",
          "componentLogLevel": "misc:error",
          "excludeIPRanges": "",
          "excludeInboundPorts": "",
          "excludeOutboundPorts": "",
          "image": "proxyv2",
          "includeIPRanges": "*",
          "includeInboundPorts": "*",
          "includeOutboundPorts": "",
          "logLevel": "warning",
          "outlierLogPath": "",
          "privileged": false,
          "readinessFailureThreshold": 4,
          "readinessInitialDelaySeconds": 0,
          "readinessPeriodSeconds": 15,
          "resources": {
            "limits": {
              "cpu": "2000m",
              "memory": "1024Mi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "startupProbe": {
            "enabled": true,
            "failureThreshold": 600
          },
          "statusPort": 15020,
          "tracer": "none"
        },
        "proxy_init": {
          "forceApplyIptables": false,
          "image": "proxyv2"
        },
        "remotePilotAddress": "",
        "sds": {
          "token": {
            "aud": "istio-ca"
          }
        },
        "sts": {
          "servicePort": 0
        },
        "tag": "1.24.3",
        "variant": "",
        "waypoint": {
          "affinity": {},
          "nodeSelector": {},
          "resources": {
            "limits": {
              "cpu": "2",
              "memory": "1Gi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "tolerations": [],
          "topologySpreadConstraints": []
        }
      },
      "hub": "",
      "image": "pilot",
      "initContainers": [],
      "ipFamilies": [],
      "ipFamilyPolicy": "",
      "istiodRemote": {
        "enabled": false,
        "injectionCABundle": "",
        "injectionPath": "/inject",
        "injectionURL": ""
      },
      "jwksResolverExtraRootCA": "",
      "keepaliveMaxServerConnectionAge": "30m",
      "memory": {},
      "meshConfig": {
        "enablePrometheusMerge": true,
        "extensionProviders": [
          {
            "name": "otel",
            "opentelemetry": {
              "port": 4317,
              "service": "otel-collector.observable.svc.cluster.local"
            }
          }
        ]
      },
      "nodeSelector": {},
      "ownerName": "",
      "pilot": {
        "cni": {
          "enabled": false
        },
        "enabled": true
      },
      "podAnnotations": {},
      "podLabels": {},
      "replicaCount": 1,
      "resources": {
        "requests": {
          "cpu": "500m",
          "memory": "2048Mi"
        }
      },
      "revision": "",
      "revisionTags": [],
      "rollingMaxSurge": "100%",
      "rollingMaxUnavailable": "25%",
      "seccompProfile": {},
      "serviceAccountAnnotations": {},
      "serviceAnnotations": {},
      "sidecarInjectorWebhook": {
        "alwaysInjectSelector": [],
        "defaultTemplates": [],
        "enableNamespacesByDefault": false,
        "injectedAnnotations": {},
        "neverInjectSelector": [],
        "reinvocationPolicy": "Never",
        "rewriteAppHTTPProbe": true,
        "templates": {}
      },
      "sidecarInjectorWebhookAnnotations": {},
      "tag": "",
      "taint": {
        "enabled": false,
        "namespace": ""
      },
      "telemetry": {
        "enabled": true,
        "v2": {
          "enabled": true,
          "prometheus": {
            "enabled": true
          },
          "stackdriver": {
            "enabled": false
          }
        }
      },
      "tolerations": [],
      "topologySpreadConstraints": [],
      "traceSampling": 1,
      "trustedZtunnelName": "",
      "trustedZtunnelNamespace": "",
      "variant": "",
      "volumeMounts": [],
      "volumes": [],
      "ztunnel": {
        "resourceName": "ztunnel"
      }
    }
  original-values: |-
    {
      "defaultRevision": "",
      "gateways": {
        "istio-egressgateway": {},
        "istio-ingressgateway": {}
      },
      "global": {
        "configValidation": true,
        "hub": "docker.io/istio",
        "istioNamespace": "istio-system",
        "tag": "1.24.3"
      },
      "meshConfig": {
        "extensionProviders": [
          {
            "name": "otel",
            "opentelemetry": {
              "port": 4317,
              "service": "otel-collector.observable.svc.cluster.local"
            }
          }
        ]
      },
      "pilot": {
        "cni": {
          "enabled": false
        },
        "enabled": true
      },
      "ztunnel": {
        "resourceName": "ztunnel"
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: This ConfigMap contains the Helm values used during
      chart rendering. This ConfigMap is rendered for debugging purposes and external
      tooling; modifying these values has no effect.
  creationTimestamp: "2025-05-22T09:51:24Z"
  labels:
    app.kubernetes.io/instance: istio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: istiod-1.0.0
    install.operator.istio.io/owning-resource: downgrade-istiod
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.26.0
    release: istio
  name: values
  namespace: istio-system
  resourceVersion: "40216434"
  uid: 52fa0871-bb4b-438d-a6b8-b8609b6c9591