apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ads-service
  namespace: istio-ingress
spec:
  gateways:
    - istio-ingress/istio-ingress-gateway
  hosts:
    - ads-service.biz-bridge.pix.com
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: ads-service.biz-bridge.svc.cluster.local
            port:
              number: 80