apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: valora-dispense
  namespace: istio-ingress
spec:
  gateways:
    - istio-ingress/istio-ingress-gateway
  hosts:
    - valora-dispense.valora.pix.com
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: valora-dispense.valora.svc.cluster.local
            port:
              number: 80