apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: valora-valora
  namespace: istio-ingress
spec:
  gateways:
    - istio-ingress/istio-ingress-gateway
  hosts:
    - valora-valora.valora.grpc.pix.com
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: valora-valora-9900.valora.svc.cluster.local
            port:
              number: 9900